server:
  port: 8881

#  spring.cloud.config.server.git.uri：配置git仓库地址
#  spring.cloud.config.server.git.searchPaths：配置仓库路径
#  spring.cloud.config.label：配置仓库的分支
#  spring.cloud.config.server.git.username：访问git仓库的用户名
#  spring.cloud.config.server.git.password：访问git仓库的用户密码
spring:
  application:
    name: config-client
  cloud:
    config:
      uri: "http://localhost:8888"
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.216:8761/eureka/
